import React from 'react';
import Layout from '@theme/Layout';
import Link from '@docusaurus/Link';
import ProgressWorkspace from '@site/src/components/ProgressWorkspace';
import styles from './index.module.css';

const cards=[
 ['01','Validate the baseline','Confirm target role, time budget and priority enterprise problem.','/idr/overview'],
 ['02','Run the 12-week sprint','Use focused weekly modules built around real senior-level evidence.','/idr/12-week-sprint'],
 ['03','Build security evidence','Complete SOC, Zero Trust, cloud, automation and governance labs.','/idr/labs'],
 ['04','Track credentials','Use selected Microsoft, AWS, Cisco and GitHub milestones as evidence.','/idr/credentials'],
 ['05','Deliver portfolio projects','Publish sanitised architecture, automation and leadership artefacts.','/idr/projects'],
 ['06','Review measurable growth','Use KPIs and mentor gates instead of course-completion alone.','/idr/kpis']
];
function Hero(){return <header className={styles.hero}><div className={styles.heroGrid}><div><p className={styles.eyebrow}>Skunkworks Academy · Individual Development Roadmap</p><h1>Welcome, <span>Desh.</span></h1><p className={styles.subtitle}>Cloud Architecture · Cybersecurity Operations · Automation · Strategic IT Leadership</p><p className={styles.lead}>Convert deep enterprise infrastructure experience into visible capability in cloud security architecture, SOC leadership, Zero Trust, infrastructure automation and technology strategy.</p><div className={styles.actions}><Link className="button button--primary button--lg" to="/idr/12-week-sprint">Start the 12-week sprint</Link><Link className="button button--secondary button--lg" to="/idr/calendar">Sync study calendar</Link><Link className="button button--secondary button--lg" to="/idr/download-and-review">Review / print IDR</Link></div><p className={styles.privacy}><strong>Public evidence rule:</strong> use synthetic or expressly authorised data only. Never publish credentials, customer information, enterprise logs or confidential architecture.</p></div><aside className={styles.summary}><div><span>Provisional pathway</span><strong>Cloud & Cybersecurity Solution Architect / Technical Lead</strong></div><div><span>Mentor / facilitator</span><strong>Raydo Matthee</strong></div><div><span>Sustainable learning load</span><strong>3–4 focused hours weekly</strong></div><div><span>Initial sprint</span><strong>12 weeks · evidence based</strong></div><div><span>Portfolio target</span><strong>6 senior-level artefacts</strong></div><div><span>North Star</span><strong>August 2027</strong></div></aside></div></header>}
export default function Home(){return <Layout title="Welcome Desh — Individual Development Roadmap" description="Desh Singh’s interactive cloud, cybersecurity, automation and strategic IT leadership roadmap."><Hero/><main className={styles.main}><section className={styles.notice}><strong>Senior-professional pathway.</strong> This IDR assumes substantial existing infrastructure and support experience. Basic content is diagnostic only; the emphasis is architecture, automation, security leadership and measurable business value.</section><section className={styles.section}><div className={styles.heading}><div><p>Immediate action</p><h2>Start with evidence, not attendance.</h2></div><span>Complete work through labs, artefacts and mentor review</span></div><div className={styles.grid}>{cards.map(([n,t,c,l])=><Link className={styles.card} to={l} key={n}><span>{n}</span><h3>{t}</h3><p>{c}</p><strong>Open →</strong></Link>)}</div></section><section className={styles.northStar}><p>12-month North Star</p><blockquote>By August 2027, Desh should be able to design and defend a secure hybrid-cloud architecture, lead a practical SOC or security-modernisation initiative, automate repeatable infrastructure controls, present risk and investment decisions to leadership, and demonstrate a credible portfolio for senior cloud, infrastructure, cybersecurity or IT-management roles.</blockquote></section><section className={styles.stats}><div><strong>12</strong><span>weekly sprint modules</span></div><div><strong>12</strong><span>credential / skill milestones</span></div><div><strong>8</strong><span>hands-on labs</span></div><div><strong>6</strong><span>portfolio projects</span></div></section><section id="workspace" className={styles.workspace}><ProgressWorkspace/></section></main></Layout>}
