import React,{useEffect,useMemo,useState} from 'react';
import styles from './ProgressWorkspace.module.css';
const key='desh-idr-progress-v1';
const weeks=Array.from({length:12},(_,i)=>`Week ${i+1}`);
const creds=['GitHub Skills','SC-200 readiness','SC-300 readiness','MD-102 readiness','AZ-104 readiness','AZ-500 readiness','AWS architecture milestone','Cisco cybersecurity milestone','PowerShell automation evidence','IaC milestone','IT governance milestone','Leadership presentation'];
const projects=['SOC Detection Pack','Zero Trust Reference Architecture','Secure Endpoint Baseline','Infrastructure-as-Code Baseline','Automation & Compliance Toolkit','Strategic Security Modernisation Brief'];
const goals=['12-week sprint','Security architecture evidence','Automation evidence','Cloud architecture evidence','Governance & risk evidence','Leadership & career conversion'];
const initial={weeks:{},creds:{},projects:{},goals:{},planned:4,actual:0,notes:''};
export default function ProgressWorkspace(){const[state,setState]=useState(initial);useEffect(()=>{try{const v=localStorage.getItem(key);if(v)setState({...initial,...JSON.parse(v)})}catch{}},[]);useEffect(()=>{try{localStorage.setItem(key,JSON.stringify(state))}catch{}},[state]);const pct=useMemo(()=>{const count=(obj,list)=>list.filter(x=>obj[x]).length/list.length;return Math.round((count(state.weeks,weeks)*.35+count(state.creds,creds)*.2+count(state.projects,projects)*.3+count(state.goals,goals)*.15)*100)},[state]);const toggle=(group,item)=>setState(s=>({...s,[group]:{...s[group],[item]:!s[group][item]}}));const exportJson=()=>{const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'});const u=URL.createObjectURL(blob);const a=document.createElement('a');a.href=u;a.download='desh-idr-progress.json';a.click();setTimeout(()=>URL.revokeObjectURL(u),500)};const reset=()=>{if(window.confirm('Reset all locally stored IDR progress?'))setState(initial)};return <div className={styles.wrap}><div className={styles.head}><div><p>Interactive workspace</p><h2>Progress, evidence and review</h2></div><div className={styles.score}><strong>{pct}%</strong><span>weighted completion</span></div></div><div className={styles.bar}><span style={{width:`${pct}%`}}/></div><p className={styles.local}>Stored only in this browser. Do not enter confidential enterprise information.</p><div className={styles.metrics}><label>Planned hours / week<input type="number" min="1" max="12" value={state.planned} onChange={e=>setState({...state,planned:Number(e.target.value)})}/></label><label>Completed hours this week<input type="number" min="0" max="20" step="0.5" value={state.actual} onChange={e=>setState({...state,actual:Number(e.target.value)})}/></label><div><span>Weekly load</span><strong>{state.actual}/{state.planned} h</strong></div></div><Checklist title="12-week sprint" items={weeks} values={state.weeks} onToggle={x=>toggle('weeks',x)}/><Checklist title="Credential / skill milestones" items={creds} values={state.creds} onToggle={x=>toggle('creds',x)}/><Checklist title="Portfolio projects" items={projects} values={state.projects} onToggle={x=>toggle('projects',x)}/><Checklist title="Development goals" items={goals} values={state.goals} onToggle={x=>toggle('goals',x)}/><label className={styles.notes}>Sanitised mentor notes<textarea rows="5" value={state.notes} onChange={e=>setState({...state,notes:e.target.value})} placeholder="Record decisions, blockers and next actions only. Do not paste sensitive logs or personal data."/></label><div className={styles.actions}><button className="button button--primary" onClick={exportJson}>Export progress JSON</button><button className="button button--secondary" onClick={()=>window.print()}>Print / save PDF</button><button className="button button--secondary" onClick={reset}>Reset local progress</button></div></div>}
function Checklist({title,items,values,onToggle}){return <section className={styles.section}><h3>{title}</h3><div className={styles.checks}>{items.map(item=><label key={item}><input type="checkbox" checked={Boolean(values[item])} onChange={()=>onToggle(item)}/><span>{item}</span></label>)}</div></section>}
